---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: opencost
spec:
  chart: opencost
  version: "1.43.2"
  sourceRef:
    kind: HelmRepository
    name: opencost
  interval: 10m0s
