---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
spec:
  chartRef:
    kind: HelmChart
    name: opencost
  releaseName: opencost
  valuesFrom:
  - kind: ConfigMap
    name: opencost-config
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
