apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: mpi-pingpong-cni
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: MPIPingPong
    spec:
      imagePullPolicy: Always
      hostNetwork: false
      # mtu: 9000
      transport: TCP
      maxlog: 25
  repetitions: 5