---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rules-config
  namespace: falco
data:
  custom-rules.yaml: |
    customRules:
      custom-rules.yaml: |-
        - macro: spawned_process
          condition: (evt.type in (execve, execveat) and evt.dir=<)
        - macro: container
          condition: (container.id != host)
        - macro: container_started
          condition: >
            ((evt.type = container or
            (spawned_process and proc.vpid=1)) and
            container.image.repository != incomplete)

        - rule: Contact K8S API Server From Container # generates a lot of noise, but is it worth having this for some namespaces?
          enabled: false
          override:
            enabled: replace
        
        - rule: Privileged Container Custom # version in incubating rules seems to trust arbitrary images
          desc: > 
            Detect the initial process initiation within a privileged container. 
          condition: >
            container_started
            and container
            and container.privileged=true
          output: Privileged container started (evt_type=%evt.type user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty %container.info)
          priority: WARNING
