apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "v4.21.1"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: falco
  valuesFrom:
  - kind: ConfigMap
    name: falco-config
  - kind: ConfigMap
    name: rules-config
